# Generated by Django 5.1.2 on 2024-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componenti'},
        ),
        migrations.AlterField(
            model_name='componente',
            name='immagine',
            field=models.URLField(max_length=500),
        ),
    ]
