# Generated by Django 5.1.2 on 2024-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_categoria_options_alter_componente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='immagine',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
