# Generated by Django 5.1.3 on 2025-02-05 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_categoria_immagine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('contenuto', models.TextField()),
                ('immagine', models.URLField(blank=True, max_length=500, null=True)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_pubblicazione'],
            },
        ),
    ]
